In [1]:
import numpy as np

### 1D Array  

In [16]:
a = np.array([1,2,3,4,5,6]) # Its 1D Array 

In [18]:
print(a)
print(a.size) # How Many element Are there

[1 2 3 4 5 6]
6


### 2D Array

In [9]:
b = np.array([(2,4,6),(1,3,5)]) # Its 2D Array

In [10]:
print(b)

[[2 4 6]
 [1 3 5]]


In [20]:
print (b.ndim) # 2D array diclire
print(a.dtype)
print(b.shape)

2
int32
(2, 3)


### Reshape

In [25]:
# When we change number of rows and column that is called reshape
C = np.array([(1,2,3,4,5),(6,7,8,9,10)])


In [26]:
print(C)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [27]:
# Change the rows and Column
C = C.reshape(5,2)

In [28]:
print(C)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
