In [24]:
import numpy as np

### 1D Array  

In [25]:
a = np.array([1,2,3,4,5,6]) # Its 1D Array 

In [26]:
print(a)
print(a.size) # How Many element Are there

[1 2 3 4 5 6]
6


### 2D Array

In [27]:
b = np.array([(2,4,6),(1,3,5)]) # Its 2D Array

In [28]:
print(b)

[[2 4 6]
 [1 3 5]]


In [29]:
print (b.ndim) # 2D array diclire
print(a.dtype)
print(b.shape)

2
int32
(2, 3)


### Reshape

In [30]:
# When we change number of rows and column that is called reshape
C = np.array([(1,2,3,4,5),(6,7,8,9,10)])


In [31]:
print(C)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [32]:
# Change the rows and Column
C = C.reshape(5,2)

In [33]:
print(C)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


### LinSpace

In [34]:
D = np.linspace(1,4,5)

In [35]:
print(D)

[1.   1.75 2.5  3.25 4.  ]


### NumPy Operations

In [36]:
E = np.array([1,2,4])

In [37]:
print(E.max())

4


In [38]:
print(E.min())

1


In [39]:
print(E.sum())

7


### Axis 

In [40]:
F = np.array([(1,2,4),(2,8,5)])

In [41]:
print(F.sum(axis = 0))

[ 3 10  9]


### Square Root 

In [42]:
print(np.sqrt(F))

[[1.         1.41421356 2.        ]
 [1.41421356 2.82842712 2.23606798]]


### Standard Deviation :

In [43]:
print(np.std(E))

1.247219128924647


### Addition :

In [44]:
F.shape

(2, 3)

### True Or False

In [45]:
Z = np.array([1,2,3,4,5])

In [46]:
Z<3

array([ True,  True, False, False, False])

In [47]:
Z>3

array([False, False, False,  True,  True])